#!/bin/bash
Tools/osx/glslc -O -fshader-stage=vertex -fpreserve-bindings -fentry-point=main -o "../Resources/Test/test.vsh.spirv" test.vsh.hlsl
Tools/osx/glslc -O -fshader-stage=fragment -fpreserve-bindings -fentry-point=main -o "../Resources/Test/test.psh.spirv" test.psh.hlsl

#Tools/osx/glslc -fshader-stage=vertex -fpreserve-bindings -fentry-point=main -fshader-stage=vertex -o "../Resources/diffuse.vsh.spirv" diffuse.vsh.glsl
#Tools/osx/glslc -fshader-stage=fragment -fpreserve-bindings -fentry-point=main -fshader-stage=fragment -o "../Resources/diffuse.psh.spirv" diffuse.psh.glsl
