using ImGuiNET;
using SKey = Silk.NET.Input.Key;
using SMouseButton = Silk.NET.Input.MouseButton;

namespace Mine.ImGuiPlugin;

public static class ImGuiInputExtensions
{
    public static ImGuiKey ToImGuiKey(SKey key)
    {
        return key switch
        {
            SKey.Unknown => ImGuiKey.None,
            SKey.ShiftLeft => ImGuiKey.LeftShift,
            SKey.ShiftRight => ImGuiKey.RightShift,
            SKey.ControlLeft => ImGuiKey.LeftCtrl,
            SKey.ControlRight => ImGuiKey.RightCtrl,
            SKey.AltLeft => ImGuiKey.LeftAlt,
            SKey.AltRight => ImGuiKey.RightAlt,
            SKey.SuperLeft => ImGuiKey.LeftSuper,
            SKey.SuperRight => ImGuiKey.RightSuper,
            SKey.Menu => ImGuiKey.Menu,
            SKey.F1 => ImGuiKey.F1,
            SKey.F2 => ImGuiKey.F2,
            SKey.F3 => ImGuiKey.F3,
            SKey.F4 => ImGuiKey.F4,
            SKey.F5 => ImGuiKey.F5,
            SKey.F6 => ImGuiKey.F6,
            SKey.F7 => ImGuiKey.F7,
            SKey.F8 => ImGuiKey.F8,
            SKey.F9 => ImGuiKey.F9,
            SKey.F10 => ImGuiKey.F10,
            SKey.F11 => ImGuiKey.F11,
            SKey.F12 => ImGuiKey.F12,
            SKey.F13 => ImGuiKey.F13,
            SKey.F14 => ImGuiKey.F14,
            SKey.F15 => ImGuiKey.F15,
            SKey.F16 => ImGuiKey.F16,
            SKey.F17 => ImGuiKey.F17,
            SKey.F18 => ImGuiKey.F18,
            SKey.F19 => ImGuiKey.F19,
            SKey.F20 => ImGuiKey.F20,
            SKey.F21 => ImGuiKey.F21,
            SKey.F22 => ImGuiKey.F22,
            SKey.F23 => ImGuiKey.F23,
            SKey.F24 => ImGuiKey.F24,
            SKey.Up => ImGuiKey.UpArrow,
            SKey.Down => ImGuiKey.DownArrow,
            SKey.Left => ImGuiKey.LeftArrow,
            SKey.Right => ImGuiKey.RightArrow,
            SKey.Enter => ImGuiKey.Enter,
            SKey.Escape => ImGuiKey.Escape,
            SKey.Space => ImGuiKey.Space,
            SKey.Tab => ImGuiKey.Tab,
            SKey.Backspace => ImGuiKey.Backspace,
            SKey.Insert => ImGuiKey.Insert,
            SKey.Delete => ImGuiKey.Delete,
            SKey.PageUp => ImGuiKey.PageUp,
            SKey.PageDown => ImGuiKey.PageDown,
            SKey.Home => ImGuiKey.Home,
            SKey.End => ImGuiKey.End,
            SKey.CapsLock => ImGuiKey.CapsLock,
            SKey.ScrollLock => ImGuiKey.ScrollLock,
            SKey.PrintScreen => ImGuiKey.PrintScreen,
            SKey.Pause => ImGuiKey.Pause,
            SKey.NumLock => ImGuiKey.NumLock,
            SKey.Keypad0 => ImGuiKey.Keypad0,
            SKey.Keypad1 => ImGuiKey.Keypad1,
            SKey.Keypad2 => ImGuiKey.Keypad2,
            SKey.Keypad3 => ImGuiKey.Keypad3,
            SKey.Keypad4 => ImGuiKey.Keypad4,
            SKey.Keypad5 => ImGuiKey.Keypad5,
            SKey.Keypad6 => ImGuiKey.Keypad6,
            SKey.Keypad7 => ImGuiKey.Keypad7,
            SKey.Keypad8 => ImGuiKey.Keypad8,
            SKey.Keypad9 => ImGuiKey.Keypad9,
            SKey.KeypadDivide => ImGuiKey.KeypadDivide,
            SKey.KeypadMultiply => ImGuiKey.KeypadMultiply,
            SKey.KeypadSubtract => ImGuiKey.KeypadSubtract,
            SKey.KeypadAdd => ImGuiKey.KeypadAdd,
            SKey.KeypadDecimal => ImGuiKey.KeypadDecimal,
            SKey.KeypadEnter => ImGuiKey.KeypadEnter,
            SKey.A => ImGuiKey.A,
            SKey.B => ImGuiKey.B,
            SKey.C => ImGuiKey.C,
            SKey.D => ImGuiKey.D,
            SKey.E => ImGuiKey.E,
            SKey.F => ImGuiKey.F,
            SKey.G => ImGuiKey.G,
            SKey.H => ImGuiKey.H,
            SKey.I => ImGuiKey.I,
            SKey.J => ImGuiKey.J,
            SKey.K => ImGuiKey.K,
            SKey.L => ImGuiKey.L,
            SKey.M => ImGuiKey.M,
            SKey.N => ImGuiKey.N,
            SKey.O => ImGuiKey.O,
            SKey.P => ImGuiKey.P,
            SKey.Q => ImGuiKey.Q,
            SKey.R => ImGuiKey.R,
            SKey.S => ImGuiKey.S,
            SKey.T => ImGuiKey.T,
            SKey.U => ImGuiKey.U,
            SKey.V => ImGuiKey.V,
            SKey.W => ImGuiKey.W,
            SKey.X => ImGuiKey.X,
            SKey.Y => ImGuiKey.Y,
            SKey.Z => ImGuiKey.Z,
            SKey.Number0 => ImGuiKey._0,
            SKey.Number1 => ImGuiKey._1,
            SKey.Number2 => ImGuiKey._2,
            SKey.Number3 => ImGuiKey._3,
            SKey.Number4 => ImGuiKey._4,
            SKey.Number5 => ImGuiKey._5,
            SKey.Number6 => ImGuiKey._6,
            SKey.Number7 => ImGuiKey._7,
            SKey.Number8 => ImGuiKey._8,
            SKey.Number9 => ImGuiKey._9,
            SKey.GraveAccent => ImGuiKey.GraveAccent,
            SKey.Minus => ImGuiKey.Minus,
            SKey.Equal => ImGuiKey.KeypadAdd,
            SKey.LeftBracket => ImGuiKey.LeftBracket,
            SKey.RightBracket => ImGuiKey.RightBracket,
            SKey.Semicolon => ImGuiKey.Semicolon,
            SKey.Apostrophe => ImGuiKey.Apostrophe,
            SKey.Comma => ImGuiKey.Comma,
            SKey.Period => ImGuiKey.Period,
            SKey.Slash => ImGuiKey.Slash,
            SKey.BackSlash => ImGuiKey.Backslash,
            _ => ImGuiKey.None,
        };
    }

	public static int ToImGuiMouseButton(this SMouseButton button)
	{
		return (int) button;
		// return button switch
		// {
		// 	SMouseButton.Left => VMouseButton.Left,
		// 	SMouseButton.Middle => VMouseButton.Middle,
		// 	SMouseButton.Right => VMouseButton.Right,
		// 	SMouseButton.Button4 => VMouseButton.Button1,
		// 	SMouseButton.Button5 => VMouseButton.Button2,
		// 	SMouseButton.Button6 => VMouseButton.Button3,
		// 	SMouseButton.Button7 => VMouseButton.Button4,
		// 	SMouseButton.Button8 => VMouseButton.Button5,
		// 	SMouseButton.Button9 => VMouseButton.Button6,
		// 	SMouseButton.Button10 => VMouseButton.Button7,
		// 	SMouseButton.Button11 => VMouseButton.Button8,
		// 	SMouseButton.Button12 => VMouseButton.Button9,
		// 	_ => VMouseButton.Left,
		// };
	}
}